"""add profile language and social links

Revision ID: ae9250aecd58
Revises: 636386d21df8
Create Date: 2026-09-06 21:51:13.944186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9250aecd58'
down_revision: Union[str, Sequence[str], None] = '636386d21df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('language', sa.String(length=30), nullable=True))
    op.add_column('user_profiles', sa.Column('facebook_url', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('instagram_url', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('linkedin_url', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('tiktok_url', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('twitter_url', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('youtube_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'youtube_url')
    op.drop_column('user_profiles', 'twitter_url')
    op.drop_column('user_profiles', 'tiktok_url')
    op.drop_column('user_profiles', 'linkedin_url')
    op.drop_column('user_profiles', 'instagram_url')
    op.drop_column('user_profiles', 'facebook_url')
    op.drop_column('user_profiles', 'language')
    # ### end Alembic commands ###
